version: '3.8'

services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Madrid}
      - SERVERURL=${SERVERURL:-vpn.example.com}
      - SERVERPORT=${SERVERPORT:-51820}
      - PEERS=${PEERS:-oliver,pc,phone}
      - PEERDNS=${PEERDNS:-1.1.1.1}
      - INTERNAL_SUBNET=${INTERNAL_SUBNET:-10.119.153.0/24}
    sysctls:
      - net.ipv4.ip_forward=1
    volumes:
      - ./configs:/config
    ports:
      - "${SERVERPORT:-51820}:${SERVERPORT:-51820}/udp"
    restart: unless-stopped

  bot:
    build: ./bot
    container_name: wireguardcontrolbot
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN:-}
      - AUTHORIZED_USERS=${AUTHORIZED_USERS:-}
      - ADMIN_CHAT_ID=${ADMIN_CHAT_ID:-}
      - WG_INTERFACE=${WG_INTERFACE:-wg0}
      - WG_CONFIG_PATH=${WG_CONFIG_PATH:-/config/wg_confs/wg0.conf}
      - WG_CLIENTS_DIR=${WG_CLIENTS_DIR:-/config/wg_confs}
      - WG_DOCKER_CONTAINER=${WG_DOCKER_CONTAINER:-wireguard}
      - WG_MTU=${WG_MTU:-1420}
      - WG_CLIENT_DNS=${WG_CLIENT_DNS:-1.1.1.1}
      - PING_INTERVAL=${PING_INTERVAL:-600}
      - USE_CLOUDFLARE=${USE_CLOUDFLARE:-false}
      - CF_API_TOKEN=${CF_API_TOKEN:-}
      - CF_ZONE_ID=${CF_ZONE_ID:-}
      - CF_RECORD_NAME=${CF_RECORD_NAME:-}
    volumes:
      - ./configs:/config
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - wireguard
    restart: unless-stopped
