services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - SERVERPORT=51820
      - PEERS=3
      - PEERDNS=1.1.1.1
      - INTERNAL_SUBNET=10.119.153.0
    volumes:
      - ./configs:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    restart: unless-stopped

  bot:
    build: ./bot
    container_name: wireguardcontrolbot
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - AUTHORIZED_USERS=${AUTHORIZED_USERS}
      - WG_INTERFACE=wg0
      - WG_CONFIG_PATH=/etc/wireguard/wg0.conf
      - WG_MTU=1420
      - WG_DOCKER_CONTAINER=wireguard
      - LOG_LEVEL=INFO
      - PING_INTERVAL=300
    volumes:
      - ./configs:/configs
      - /etc/wireguard:/etc/wireguard
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - wireguard
    restart: unless-stopped
